### ISSUE TITLE
install failed E0658

### ISSUE THREAD

**Issue by gaon12** [xforce/neox-tools#15]
I executed instruction `cargo build --release` and then I executed instruction `cargo install --path .`.

When I run `cargo build --release` command, It does not show any error message, but run `cargo install --path .`, it show error message.

Here is the message of the error.
```
  Installing npktool v0.1.0 (/home/hello/neox2)
    Updating crates.io index
   Compiling clap v3.0.0
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0/src/lib.rs:8:39
  |
8 | #![cfg_attr(feature = "derive", doc = include_str!("../README.md"))]
  |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `npktool v0.1.0 (/home/hello/neox2)`, intermediate artifacts can be found at `/home/hello/neox2/target`

Caused by:
  could not compile `clap`

To learn more, run the command again with --verbose.
```

What should I do?

**Comment by gaon12** [comment]
I run on Windows, it runs with some bug, but this error does not displayed.

**Comment by coolagrwal** [comment]
kindly share, how you resolved this issue

**Comment by gaon12** [comment]
> kindly share, how you resolved this issue

 When WSL2 (Ubuntu), the above error occurred.

However, in a Windows environment, If you install "[rust](https://www.rust-lang.org)" and enter the command again, the above problem does not appear.

**Comment by coolagrwal** [comment]
Cool, will try it, even i tried it somehow it worked once on client but
when i kick in miner it errors. Something is funky
