### ISSUE TITLE
Support for multiple file params 

### ISSUE THREAD

**Issue by wereii** [xforce/neox-tools#2]
Hi, awesome tool, just something that might be be useful:

Example
```bash
$ npktool x res0.npk res10.npk res11.npk
```
which does not work, not even with `--` separator. Right now I had to use shell `for` to apply it on multiple files.
I see it might clash with the out dir, so it's up to you.

Thanks 
W

**Comment by xforce** [comment]
Sorry for the late response, yes this does make sense.

I have decided to change the command line interface in 91845cd4966388a5323ab0db59dce6f59dc6657c
along with support for embedded filelist files (at least those are a thing in Eve Echoes, not sure about other NetEase games).

So now the outdir is an option `-d <dir>`
