### ISSUE TITLE
build error!

### ISSUE THREAD

**Issue by x4317350** [xforce/neox-tools#7]
cargo build --release
   Compiling npktool v0.1.0 (/Users/rcy/Downloads/neox-tools-e958fa3c51c41e17d1056f55892e2d37be122e72 2)
warning: unused import: `error`
 --> src/main.rs:3:18
  |
3 | use log::{debug, error, info, trace, warn};
  |                  ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `ProgressIterator`
   --> src/main.rs:591:42
    |
591 |             use indicatif::{ProgressBar, ProgressIterator, ProgressStyle};
    |                                          ^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/main.rs:552:9
    |
551 |     match matches.subcommand() {
    |           -------------------- this expression has type `(&str, std::option::Option<&clap::ArgMatches>)`
552 |         Some(("x", sub_m)) => {
    |         ^^^^^^^^^^^^^^^^^^ expected tuple, found enum `std::option::Option`
    |
    = note: expected tuple `(&str, std::option::Option<&clap::ArgMatches>)`
                found enum `std::option::Option<_>`

error[E0308]: mismatched types
   --> src/main.rs:681:9
    |
551 |     match matches.subcommand() {
    |           -------------------- this expression has type `(&str, std::option::Option<&clap::ArgMatches>)`
...
681 |         Some(("p", _)) => unimplemented!("Packing is currently not supported"),
    |         ^^^^^^^^^^^^^^ expected tuple, found enum `std::option::Option`
    |
    = note: expected tuple `(&str, std::option::Option<&clap::ArgMatches>)`
                found enum `std::option::Option<_>`

error: aborting due to 2 previous errors; 2 warnings emitted

For more information about this error, try `rustc --explain E0308`.
error: could not compile `npktool`.

To learn more, run the command again with --verbose.

**Comment by xforce** [comment]
Sorry about that, this should be fixed in latest master, I forgot to update the lock file, so it was using an old version of a dependency.
