### ISSUE TITLE
decompiling pyc error with uncompyle6

### ISSUE THREAD

**Issue by x4317350** [xforce/neox-tools#8]
I decompiled the PYC file with Uncompyle6, but made an error.
I have uploaded pyC file. Could you please help me check the error when you are free? Thank you！

[ui_new.main.main_ui.pyc.zip](https://github.com/xforce/neox-tools/files/5339082/ui_new.main.main_ui.pyc.zip)

**Comment by xforce** [comment]
This works fine with the tools provided in this repo.
Make sure to use my Uncompyle6 fork (included as submodule, and will be used if cloned correctly), which has support for some non-standard Python opcodes.

**Comment by xforce** [comment]
Is there anything that remains here?

**Comment by x4317350** [comment]
thanks! It can work now.i can decompiled the pyc with Uncompyle6 fork~

**Comment by x4317350** [comment]
your are good man!
